### ISSUE TITLE
Error when plotting fractional powers

### ISSUE THREAD

**Issue by fny** [mauriciopoppe/function-plot#100]
I'm getting the following error when upgrading from 1.4.0 to 1.18.1:

"Power is not an integer, you should use nth-root instead, returning an empty interval"

I've created a JSBin which produces the issue. Note that the large number of warnings generated will likely cause your browser to crash: https://jsbin.com/roruha/15/edit

Here's the same graph using the v1.4 library:
https://jsbin.com/roruha/17/edit?html,js,output

Changing the 3rd parameter in curveSet(a, p, ...) to a non integer should trigger the issue.

**Comment by mauriciopoppe** [comment]
Thanks for the report, I've added the following to your demo to make it work:

```javascript
    return { fn: curve, graphType: 'polyline' }
```

The explanation: function-plot uses interval arithmetic by default, it was expecting a function that returns intervals instead of numbers, using graphType forces it to use the arithmetic we use every day.

I'm sorry I don't keep a proper changelog, this should be a breaking API change so I should release v2 with these changes, however, I'm also planning to rewrite parts of the library and that may take some time
