### ISSUE TITLE
Bar Data

### ISSUE THREAD

**Issue by oliveira-filipe** [mauriciopoppe/function-plot#115]
Hi, i have a school work where i need to explain [Integral](http://mathworld.wolfram.com/Integral.html)

The user will input the formula/function and some other values, so i have to plot the following chart:
![image](https://user-images.githubusercontent.com/22033274/36951306-da51d76c-1fe0-11e8-8671-fd96a40c7668.png)

Your library, so far, is the only function plotter that i found. 

I read the docs, and i could not find any option to pass some other data to the chart like:
```
data: {
        columns: [
            ['data1', 30, 20, 50, 40, 60, 50],
        ],
        type: 'bar'
    }
```

Is there any way to plot data like this? If not, is there any way to plot a formula in C3 or Google Charts?

Thank you

**Comment by mauriciopoppe** [comment]
It's doable, in fact I did something like that in one of the articles of my blog: https://www.mauriciopoppe.com/notes/mathematics/calculus/integral/, however this works because of a little trick of interval arithmetic, you should use a different library to plot bar charts like https://beta.observablehq.com/ or https://plot.ly/
