### ISSUE TITLE
Can I use function-plot to extract points?

### ISSUE THREAD

**Issue by sriram15690** [mauriciopoppe/function-plot#123]
Can I use function-plot only to extract co-ordinates? My applications has many custom UI requirements like the size of Axis, the size of the visual-grid etc. Hence,  I want to use another graph/chart library for drawing the chart.

**Comment by mauriciopoppe** [comment]
hey, the evaluator module is unfortunately tightly coupled with the renderer (which is a bad design), the evaluators are in the folder `lib/samplers/`, the signature of each evaluator is:

```js
evaluator(chart, datum, range, nSamples)

chart = an instance of function plot
datum = a datum of the data array
range = an array with the left/right ends
nSamples = the number of samples to take
```

For some evaluators you could mock the `chart` object with the required properties (properties like `chart.meta.yScale` which is an instance of `d3.scale.linear` or `d3.scale.log`, etc)

As for the reason I had to do this was that the evaluator needed some information about the chart itself but instead of sending only what was necessary I sent the whole chart instead :(
