### ISSUE TITLE
functions with abs - interval graphtype

### ISSUE THREAD

**Issue by belezariusz** [mauriciopoppe/function-plot#162]
It seems that there is an error for asymptotic functions with absolute value. The problem occures with interval graph type. 
for example: "abs(1/x)" gives an additional line on 0.

**Comment by mauriciopoppe** [comment]
thanks for the report and sorry for the late response, this is an interesting case in the interval arithmetic world, when `f(x) = 1/x` and we evaluate it with a range that contains zero `f([-0.001, 0.001])` should result in `[-infinity, infinity]` because we're evaluating all the numbers between -0.001 and 0.001, e.g. 1/-1e10, 1/-1e11, ... 1/-0 https://github.com/mauriciopoppe/interval-arithmetic/blob/e49d3f83ae119d1f4fd367ad0e05092fb5b501f6/src/operations/arithmetic.test.ts#L205-L230

I think that the interval arithmetic library behavior is ok however this library might need to do something to account for that case when it detects the `abs` function

**Comment by mauriciopoppe** [comment]
fixed in https://github.com/mauriciopoppe/interval-arithmetic/issues/26, released in https://github.com/mauriciopoppe/function-plot/releases/tag/v1.22.5
