### ISSUE TITLE
Thick graph line

### ISSUE THREAD

**Issue by K-Lorenz** [mauriciopoppe/function-plot#177]
When Rendering a function like: f(x)=1/3x^3-***x^2***
![image](https://user-images.githubusercontent.com/86967062/147718139-1f30219a-4c31-4bbb-baae-0a3b3502f58f.png).
A weird thick line appears.
![Screenshot from 2021-12-30 04-04-12](https://user-images.githubusercontent.com/86967062/147718457-4327f30a-852f-4c45-9e8f-8ac44c049576.png)
The pointer seems to mapped ok though.
This doesn't happen if use a simpler function. f(x)=1/3x^3 works just fine.
![Screenshot from 2021-12-30 04-08-04](https://user-images.githubusercontent.com/86967062/147718574-0738f341-be6c-4c3a-a605-810745c61445.png)
Code for the function:
```
functionPlot({
            target: '#curve-1',
            data: [{
                fn: '1/3x^3-x^2'
            }],
            yAxis: {domain: [-21, 4]},
            xAxis: {domain: [-25, 25]},
            })
      }, []);
```

**Comment by mauriciopoppe** [comment]
I've seen this before and it's because of the nature of doing operations with interval arithmetic which is what this library uses by default, what's happening is that operations with intervals carry some error (e.g. exponentiation, addition, etc), in fact the guarantee that you have with interval arithmetic is that the **true graph is guaranteed to be inside the graph bounds** (more info in the summary in the webpage and in the [interval arithmetic library README.md](https://github.com/mauriciopoppe/interval-arithmetic)).

To use regular arithmetic please add `graphType: 'polyline'` to the options.

**Comment by K-Lorenz** [comment]
Oh, interesting.
Thanks for the fix and fast reply.
