### ISSUE TITLE
`graphType` expected when `fnType` is `polar`

### ISSUE THREAD

**Issue by leonhma** [mauriciopoppe/function-plot#224]
While developing, I came across a bug. This is my input to `functionPlot()`:

![Screenshot_20230111_180128](https://user-images.githubusercontent.com/67312077/211870765-c35200c2-18a4-4b45-90ce-c64442f4aca3.png)

And as you can see, this raises an error about 'polar not being supported in interval sampler'.

I didn't specify a sampler in my input to `functionPlot`, so I would expect it to default to `polyline`.

### Versions

![Screenshot_20230111_180420](https://user-images.githubusercontent.com/67312077/211871227-e1f6ab69-a540-4704-a387-b1f5d94c1a9e.png)

Edit: The same happens with `graphType=vector`. Same error that interval is not supported

**Comment by mauriciopoppe** [comment]
polar and vector are only supported in the `polyline` graphType https://github.com/mauriciopoppe/function-plot/blob/master/src/samplers/builtIn.ts#L171-L175, by default the sampler is `interval`. I made that decision because that was the main feature of this library.

The graph type `interval` supports implicit and linear https://github.com/mauriciopoppe/function-plot/blob/master/src/samplers/interval.ts#L115-L116

**Comment by leonhma** [comment]
I know about that. I just think that functionplot should default to polyline if interval doesn't work (fnType is vector or polar). I can make a PR to put in a if-clause if you want.

**Comment by mauriciopoppe** [comment]
sounds good to me, I think that the strategy could be: 
- check if the graphType is in the interval sampler, if so default to it
- if not then check if it's on the builtIn sampler, if so default to it
- if not then throw an error
