### ISSUE TITLE
Including a 'class' attr causes line ghosting

### ISSUE THREAD

**Issue by adamvanaken** [mauriciopoppe/function-plot#229]
The path and/or line elements in the content graph are added every zoom/pan redraw, rather than updated/replaced.

Steps to reproduce:

1. Open the code sandbox from the docs: https://codesandbox.io/s/muddy-cdn-ibl5x?from-embed

2. Add a `class` attribute:

![image](https://user-images.githubusercontent.com/5086278/232089247-08f0671a-73eb-438d-a949-04e27a1c5db0.png)

3. Pan/zoom graph and notice the ghosting:

![image](https://user-images.githubusercontent.com/5086278/232089367-f5d65aed-904a-4453-b257-7c54781a28c1.png)

**Comment by mauriciopoppe** [comment]
I believe this is happening because setting `data.*.attr.class` is [overriding the class set by functionPlot on each datum](https://github.com/mauriciopoppe/function-plot/blob/500e94acdeae8e7134c017e5eb699ab1f3d71a90/src/graph-types/polyline.ts#L80-L85) so when there's the d3 data binding it appears to functionPlot that [this is a new datum](https://bost.ocks.org/mike/selection/).

A small workaround would be to merge the class with functionPlot's class, on the downside it'd not be possible to remove a class on update, I think that could work.

**Comment by mauriciopoppe** [comment]
It should be fixed in https://github.com/mauriciopoppe/function-plot/releases/tag/v1.23.3, thanks for the bug report 🙏🏼.
