### ISSUE TITLE
Problem plotting: x/((x^2+x)/(x-4))

### ISSUE THREAD

**Issue by minoush82** [mauriciopoppe/function-plot#233]
Plotting the function `x/((x^2+x)/(x-4))` with the following configuration:
```
functionPlot({
    target: '#graph',
    data: [{
        fn: 'x/((x^2+x)/(x-4))'
     }]
})
```

yields some strange data points in one part of it. The following shows some undesired clustering of data points:
![bad](https://github.com/mauriciopoppe/function-plot/assets/90900973/8d34e987-fd4d-4710-9327-177cb8501f42)

Adding `graphType: 'polyline'` does not change a thing.
```
functionPlot({
    target: '#graph',
    graphType: 'polyline',
    data: [{
        fn: 'x/((x^2+x)/(x-4))'
    }]
})
```

Plotting the simplified version `(x-4)/(x+1)` of the previous function gives the desired graph.
![good](https://github.com/mauriciopoppe/function-plot/assets/90900973/1f81c592-bd50-4bf7-a80f-8ee31c5f0e0c)

**Comment by mauriciopoppe** [comment]
`graphType` is a property of data, not of the top object, this works for me:

```js
functionPlot({
  target: '#root',
  data: [{
      fn: 'x/((x^2+x)/(x-4))',
      graphType: 'polyline',
  }]
})
```

The clustering of points is because of interval-arithmetic and the operations that are being carried over (lots of numbers considered because of the division). That's one of the tradeoffs with the internal graphType plotter.

**Comment by minoush82** [comment]
Many thanks.
