### ISSUE TITLE
Latex in Function-Plot Title

### ISSUE THREAD

**Issue by minoush82** [mauriciopoppe/function-plot#237]
Is it possible to pass latex to the option parameter "title"? At the top of the README.md file in this repository, two graphs are shown with nicely-rendered titles. How do I achieve a similar result?

**Comment by mauriciopoppe** [comment]
The example that you see is https://www.mauriciopoppe.com/notes/mathematics/calculus/derivative/#maximaminima, I rendered latex through MathJax and positioned on top of the graphs so that they look like they're the title.

You could transform a title that's delimited with $$ and then process it with MathJax's SVG renderer, I haven't tried this though
