### ISSUE TITLE
Logarithm function cannot be plotted using graph type "polyline" or "scatter"

### ISSUE THREAD

**Issue by minoush82** [mauriciopoppe/function-plot#239]
I am having some issues plotting the function `ln`.
The following does not work:
```
functionPlot({       
        target: '#graph',       
        data: 
        [   
            {fn: 'ln(x)', graphType: 'polyline'}
        ]
    });
```
neither does the following:
```
functionPlot({       
        target: '#graph',       
        data: 
        [   
            {fn: 'ln(x)', graphType: 'scatter'}
        ]
    });
```
but the following works:
```
functionPlot({       
        target: '#graph',       
        data: 
        [   
            {fn: 'ln(x)', graphType: 'interval'}
        ]
    });
```
as does the following:
```
functionPlot({       
        target: '#graph',       
        data: 
        [   
            {fn: 'ln(x)'}
        ]
    });
```
I generate the graphs automatically, and I would like to use `polyline` as my `graphType` consistently. Anyway to achieve this with the function `ln`?

**Comment by mauriciopoppe** [comment]
I think this is happening because the polyline and scatter graphTypes by default use [properties in the `Math` object](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math), if you read these docs you'll see that the equivalent to `ln` is the [`log` function](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/log).

These two graphs have the same result:

```javascript
functionPlot({
  target: "#root",
  data: [
    {
      fn: "log(x)",
      graphType: 'polyline'
    },
    {
      fn: 'ln(x)'
    }
  ]
});
```

I defined [`ln` for interval arithmetic here](https://github.com/mauriciopoppe/interval-arithmetic/blob/d05a8d01209a7fdf249f89a567edc040bad80c79/src/operations/misc.ts#L57) so that's why `ln` works in the interval graphType (interval is the default graphType).
