### ISSUE TITLE
Issues with closed path when used with `sampler:'builtIn'` (math.js) and `graphType: 'polyline'`

### ISSUE THREAD

**Issue by bornova** [mauriciopoppe/function-plot#249]
Hi, thank you for this great plotting library.  I have been using it for a few years now and really appreciate you putting in the time to maintain it.  To the issue...

Unexpected results are displayed when using different combinations of `sampler: 'builtIn'`, `closed: true` and `graphType: 'polyline'`.  Take following examples:

This works fine:
```javascript
functionPlot({
  target: '#closed',
  xAxis: {domain: [-10, 10]},
  data: [{
    fn: '3 + sin(x)',
    closed: true
  }]
})
```
No plot line or area is displayed.  Blank plot but tip will still track correct path:
```javascript
functionPlot({
  target: '#closed',
  xAxis: {domain: [-10, 10]},
  data: [{
    fn: '3 + sin(x)',
    closed: true,
    sampler: 'builtIn' // Variable 'math' is in window global scope
  }]
})
```
Area is shaded but plot is shifted:
```javascript
functionPlot({
  target: '#closed',
  xAxis: {domain: [-10, 10]},
  data: [{
    fn: '3 + sin(x)',
    closed: true,
    graphType: 'polyline'
  }]
})
```
Here is a codesandbox where you can see this in action:
https://codesandbox.io/s/dry-breeze-lq2765?file=/src/index.mjs

Also I think `sampler: 'builtIn'` is a bit confusing.  It gives the impression the built in parser is meant to be used not math.js.  I would suggest changing this option to `sampler: 'mathjs'` or something similar instead.

**Comment by mauriciopoppe** [comment]
A few of these options are incompatible, I'll try to summarize the outcomes:

- `sampler: 'builtIn', graphType: polyline` is the only option for the builtIn sampler, that's because the builtIn sampler evaluates a function and gets an array of numbers e.g. if `f(x)=x^2` evaluated at `[-2,0,2]` would give you the output `[4,0,4]`.
- `sampler: 'builtIn', closed: true` wouldn't work because the default `graphType: 'interval'`. Using the example above you'd be giving the output `[4,0,4]` to a plotter that works with an array of intervals e.g. `[Interval(lo_0, hi_0), Interval(lo_1, hi_1), ...]`
- `closed: true, graphType: 'polyline'` very curious output 😅. I don't think I've ever tried this and it needs investigation, my mental model would be that a closed graph needs an array of lower and upper bounds e.g. `[[0, 5], [0, 4], ...]` which matches what an interval is, therefore I think `closed: true` should work with the `graphType: 'interval'` only. At least for now.

About the API, totally agreed, when I worked on this I thought that using mathjs should happen transparently when you used the builtIn sampler so it's very confusing to know that if you import mathjs then function-plot might start using it without you knowing, if a change like this is made then I guess it'd be breaking so maybe in the 2.0.0 version 😕

**Comment by bornova** [comment]
Hi @mauriciopoppe,
Thanks for the explanation!
