### ISSUE TITLE
instance meta margin not being set

### ISSUE THREAD

**Issue by jcandan** [mauriciopoppe/function-plot#74]
expected behavior:
the following should redraw the chart with a new bottom margin:

```
instance.meta.margin.bottom = 40;
instance.draw();
```

current behavior:
the new margin is not applied.

possible solution:
in `lib/index.js`, `build()` is only called once on init. it's the only time that the `internalVars()` method is called which is where the `meta.margin` object is set to the instance margin. a call to `internalVars()` should be added to the `draw()` method.

**Comment by maurizzzio** [comment]
`instance.draw` only redraws everything inside `data`, if you modify an option outside this field you should call `build` instead, however, the following won't work

```js
instance.meta.margin.bottom = 40;
instance.build();
```

This is because `build` recomputes all the properties of `meta`, in fact `meta` should be read only as far as I remember.

I'm going to tinker about a good solution for this problem since I want `draw` to only draw data, I think that there should be another method which redraws everything but also doesn't recompute everything from scratch.
