### ISSUE TITLE
control point rendering for scatterplot points

### ISSUE THREAD

**Issue by Sigfried** [mauriciopoppe/function-plot#76]
Is it possible/feasible to intercept the drawing of points for point functions? 

Maybe the library renders a 'g' element and could pass that to a renderer, or perhaps it could just pass svg coordinates, along with the data item.

I guess currently the point function expects an array of [x,y] values; what I'm asking for would probably mean that it expects either an array of objects that have their own x and y properties or an array of objects along with x and y accessor functions -- and, of course the rendering function.

So the rendering function(s?) would be able to define: 1) the svg element generated for that point (circle, rect, path, etc.), and 2) attributes/styles to apply (fill, stroke, transforms, mouseovers, etc.)

I'd like to replace a scatterplot library I'm writing with function-plot, but I need control of point shape, color, size, tooltip.

Amazing library! If what I want isn't feasible, maybe I'll be able to steal/copy bits of it so I can draw functions on top of my existing charts.

**Comment by maurizzzio** [comment]
Thanks for reaching out, sadly I'm quite busy right now, I'll give you an elaborate answer next weekend

**Comment by maurizzzio** [comment]
When I created this library my initial purpose was to render only functions, the design was quite simple, I only needed a function in the form `y = f(x)` which when evaluated with some specific values it creates an array of tuples to render e.g. `data = [ [x0, f(x0)], [x1, f(x1)], ...]`.

After that data is computed it can be rendered using a lot of `<circle>` elements to create a scatterplot like graph or join the points and create a `<path>` element to create a polyline.

A few time later, I also needed to render a lot of points/vectors which clearly don't have the form `y = f(x)` however instead of modifying the workings of the library I coded a workaround: skip the evaluation phase and use the input as the data e.g. `data = [ [x0, y0], ... ]` which is what you send to the library inside the `data`.

As you see the problem right now with the state of the library is that it's designed to render functions and not to render other stuff like random points or vectors even though it's capable of doing so.

However, you can always make your own render function which suits to your needs but it needs direct modification of the source, the steps would be:

- create a file like https://github.com/maurizzzio/function-plot/blob/master/lib/graph-types/scatter.js which defines whatever you need to render
- add a reference to it here: https://github.com/maurizzzio/function-plot/blob/master/lib/graph-types/index.js, e.g.

```js
module.exports = {
  polyline: require('./polyline'),
  interval: require('./interval'),
  scatter: require('./scatter'),
  myRenderer: require('./my-custom-renderer')
}
```

And that's it! You have to create an instance of functionPlot like this:

```js
functionPlot({
  data: [{
    graphType: 'myRenderer'
  }]
})
```

I'm really sorry if you have to do it this way, it's a design problem that I'm planning on solving on a library based on this one which should solve all these `extension` problems.

**Comment by Sigfried** [comment]
Thank you so much for this and sorry I haven't responded earlier. I haven't had a chance to get back to this project yet, but when I do, I'll try following your suggestions.
