### ISSUE TITLE
3d plotting?

### ISSUE THREAD

**Issue by ttks** [mauriciopoppe/function-plot#89]
Hi,

This looks amazing!

I work at a lab where we support new ways of teaching mathematics at university - building interactive apps that help students play around to get an intuitive feel for the concepts being taught.

I started writing code (using d3js) for what you've already done, so that's awesome.

The next step for us is 3D plotting - as we move into exploring spheres, cones, cylinders.

Do you have any plans in that direction?

Thanks!

**Comment by maurizzzio** [comment]
Thanks, actually I did at some point but I didn't implement it because I started working on another project, I was planning on implementing it with http://stack.gl/ but it's still on my TODO list, I'd highly recommend https://plot.ly/ or https://github.com/regl-project/regl as the renderer and perhaps some parts of function-plot for function evaluation

**Comment by rafaelferreiraql** [comment]
Seconded! I find it surprising that there seems to be no library oriented for 3D function graphing in Javascript (and very few for 2D, yours being one of them, and probably the best)
